### ISSUE TITLE
Downgrade?

### ISSUE THREAD

**Issue by ManicQuinn** [acikek/pescatore#1]
Any plans to downgrade to 1.20.1? I wanna use this mod but a lot of my mods are not up to date with 1.20.4, and fishing is the only mod that is on 1.20.4, at least for my list of mods(apart from optimizations)

**Comment by OlaPessoa** [comment]
i'd really like this mod to be downgraded to 1.20.1, i love it and it fixes one of the main issues minecraft has... fishing... i also would love to see the team that made pescatore work on a farming mod which is also just boring and oversimplified in a way that's a actual boring thing to do (like vanilla fishing)

**Comment by Mapter322** [comment]
1.20.1 please!!!!

**Comment by acikek** [comment]
Done, have fun

**Comment by OlaPessoa** [comment]
Ty <3
